# Starter kit includes 3 Simple Bandages and 1 Grenade.
starter_kit : true

prefix : "ยง7[MCZombies] "

# Disable or Enable items below
simple_bandage : true
advanced_bandage : true
grenade : true
molotov : true

# Item Settings
grenade_radius: 3
molotov_radius: 1

# Recipe Settings
custom_recipes : true
steel_nugget_cook_time: 7.5 #In Seconds